rootProject.name = "fact-checker"
include("fact-checker-api")
include("core")
include("utils")
include("ext")
include("config")
include("cli")
include("web-service")
include("web-ui")
include("sparql-dsl")
include("owl-verbalizer")
project(":owl-verbalizer").projectDir = File("owl-verbalizer", "java")
include("owl-verbalizer-jvm")
project(":owl-verbalizer-jvm").projectDir = File("owl-verbalizer", "jvm")
include("fact-checker-application")
